build:
  image: gcc
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script: 
    - ci/po-install.sh
  script: 
    - ci/gitlab_build.sh
  artifacts:
    paths:
      - bin/
    when: on_success

# run tests using the binary built before
test:
  image: gcc
  stage: test
  script:
    - ci/gitlab_test.sh
